[package]
name = "landscape2"
description = "Landscape2 CLI tool"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
rust-version = "1.70"

[dependencies]
anyhow = "1.0.71"
askama = "0.12.0"
clap = { version = "4.3.1", features = ["derive"] }
hex = "0.4.3"
lazy_static = "1.4.0"
regex = "1.8.3"
reqwest = "0.11.18"
rust-embed = "6.6.1"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
serde_yaml = "0.9.21"
sha2 = "0.10.6"
time = { version = "0.3.21", features = [
    "formatting",
    "macros",
    "parsing",
    "serde",
] }
tokio = { version = "1.28.2", features = [
    "macros",
    "process",
    "rt-multi-thread",
    "signal",
    "time",
] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
